[2024-08-29 00:17:32,292] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-29 00:17:32,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-29 00:17:32,299] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-29 00:17:32,299] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-29 00:17:32,299] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-29 00:17:32,313] {taskinstance.py:1377} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2024-08-27 00:00:00+00:00
[2024-08-29 00:17:32,316] {standard_task_runner.py:52} INFO - Started process 44760 to run task
[2024-08-29 00:17:32,319] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2024-08-27T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmp99r5pali', '--error-file', '/tmp/tmpkmtj_ip1']
[2024-08-29 00:17:32,319] {standard_task_runner.py:80} INFO - Job 33: Subtask twitter_datascience
[2024-08-29 00:17:32,356] {task_command.py:370} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-08-27T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-29 00:17:32,395] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=TwitterDAG
AIRFLOW_CTX_TASK_ID=twitter_datascience
AIRFLOW_CTX_EXECUTION_DATE=2024-08-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-27T00:00:00+00:00
[2024-08-29 00:17:32,404] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/airflow_twitter/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/airflow_twitter/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_connection_default` isn't defined
[2024-08-29 00:17:32,406] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, execution_date=20240827T000000, start_date=20240829T031732, end_date=20240829T031732
[2024-08-29 00:17:32,412] {standard_task_runner.py:92} ERROR - Failed to execute job 33 for task twitter_datascience (The conn_id `twitter_connection_default` isn't defined; 44760)
[2024-08-29 00:17:32,454] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-29 00:17:32,471] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-29 00:27:29,085] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-29 00:27:29,093] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-29 00:27:29,093] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-29 00:27:29,094] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-29 00:27:29,094] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-29 00:27:29,105] {taskinstance.py:1377} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2024-08-27 00:00:00+00:00
[2024-08-29 00:27:29,107] {standard_task_runner.py:52} INFO - Started process 48384 to run task
[2024-08-29 00:27:29,110] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2024-08-27T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpvohc50yl', '--error-file', '/tmp/tmp2e9_miqr']
[2024-08-29 00:27:29,111] {standard_task_runner.py:80} INFO - Job 43: Subtask twitter_datascience
[2024-08-29 00:27:29,153] {task_command.py:370} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-08-27T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-29 00:27:29,198] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=TwitterDAG
AIRFLOW_CTX_TASK_ID=twitter_datascience
AIRFLOW_CTX_EXECUTION_DATE=2024-08-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-27T00:00:00+00:00
[2024-08-29 00:27:29,202] {base.py:68} INFO - Using connection ID 'twitter_connections_default' for task execution.
[2024-08-29 00:27:29,203] {twitter_hook.py:34} INFO - URL: https://labdados.com/2/tweets/search/recent?query=datascience&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,lang,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2024-08-27T00:00:00.00Z&end_time=2024-08-28T00:00:00.00Z
[2024-08-29 00:27:30,085] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=TwitterDAG, task_id=twitter_datascience, execution_date=20240827T000000, start_date=20240829T032729, end_date=20240829T032730
[2024-08-29 00:27:30,131] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-29 00:27:30,146] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
